language: rust
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
rust:
  - stable
before_script:
   - rustup component add clippy
script:
   - cargo clippy
   - cargo test